#pragma once
#include <cstdint>

// mu-Tant's license identity, passed to mu_core::LicenseManager::check. Kept product-side
// (not in mu-core) so the shared verifier stays plugin-agnostic. The embedded value is the
// PUBLIC key only — the private signing key never lives in the repo.
namespace mu_tant
{
    // Must match the `product=` field the signer writes + the Lemon Squeezy product
    // (LS product id 1134546).
    inline constexpr const char* kLicenseProductId = "mu-Tant";

    // License file the user drops into the content dir (getContentDir()).
    inline constexpr const char* kLicenseFilename  = "mutant.lic";

    // 32-byte Ed25519 public key. Paired with tools/keys/mutant.key (git-ignored secret),
    // generated by MuLicenseTool; the matching .lic is signed by that tool.
    inline constexpr uint8_t kLicensePublicKey[32] = {
        0x4d, 0xb8, 0xa4, 0x97, 0x52, 0xf3, 0x5d, 0x78, 0xa0, 0xfa, 0x7a, 0x38, 0x0a, 0x01, 0xb5, 0x1c,
        0x69, 0x76, 0x11, 0xd8, 0xe4, 0x4e, 0x03, 0xa8, 0x44, 0x76, 0xda, 0x15, 0xa9, 0x92, 0xf1, 0x69,
    };
}
