#pragma once
#include <cstdint>

// mu-Clid's license identity, passed to mu_core::LicenseManager::check. Kept product-side
// (not in mu-core) so the shared verifier stays plugin-agnostic. The embedded value is the
// PUBLIC key only — the private signing key never lives in the repo.
namespace mu_clid
{
    // Must match the `product=` field the signer writes + the Lemon Squeezy product.
    inline constexpr const char* kLicenseProductId = "mu-Clid";

    // License file the user drops into the content dir (getContentDir()).
    inline constexpr const char* kLicenseFilename  = "muclid.lic";

    // 32-byte Ed25519 public key. Paired with tools/keys/muclid.key (git-ignored secret),
    // generated by MuLicenseTool; the matching .lic is signed by that tool.
    inline constexpr uint8_t kLicensePublicKey[32] = {
        0xb5, 0x89, 0x7f, 0x7f, 0x0d, 0x64, 0xb0, 0x59, 0xca, 0x6a, 0x60, 0xfa, 0x6f, 0x65, 0x7a, 0xa0,
        0x9b, 0x10, 0x4b, 0x0f, 0x10, 0xa4, 0xe7, 0x7e, 0xbc, 0x96, 0x92, 0x84, 0x7a, 0x9a, 0x53, 0x34,
    };
}
